"""some changes

Revision ID: 157b4bc462b1
Revises: 7abb9053870b
Create Date: 2025-10-02 00:47:48.104054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "157b4bc462b1"
down_revision: Union[str, Sequence[str], None] = "7abb9053870b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "camp", sa.Column("name", sa.String(length=30), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("camp", "name")
    # ### end Alembic commands ###
