"""something

Revision ID: d2e32acb6343
Revises: 157b4bc462b1
Create Date: 2025-10-02 01:16:26.911613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2e32acb6343"
down_revision: Union[str, Sequence[str], None] = "157b4bc462b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commentary", sa.Column("review_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "commentary", "review", ["review_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "commentary", type_="foreignkey")
    op.drop_column("commentary", "review_id")
    # ### end Alembic commands ###
